from __future__ import annotations

from typing import Any, Optional, Protocol


class Repository(Protocol):
    def list(self, filters: Optional[dict[str, Any]] = None) -> list[dict[str, Any]]: ...
    def get(self, id: str) -> Optional[dict[str, Any]]: ...
    def create(self, entity: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, id: str, patch: dict[str, Any]) -> dict[str, Any]: ...
    def append_audit(self, event: dict[str, Any]) -> None: ...
